language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t aakashp729/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aakashp729/docker-react npm run test
